# github workflow to automate builds

name: ReviveEmu build

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    name: ${{ matrix.name }}

    # The type of runner that the job will run on
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - name: "Windows 32-bit"
            arch: "Win32"
            bindir: "Release"
            outname: "ReviveEmu-Win32"
          - name: "Windows 64-bit"
            arch: "x64"
            bindir: "x64\\Release"
            outname: "ReviveEmu-Win64"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        shell: cmd
        working-directory: Steam
        run: MSBuild -m Steam.sln -t:Steam:Rebuild -p:Configuration=Release -p:Platform=${{ matrix.arch }}

      - name: Prepare files for packaging
        shell: cmd
        run: |
          mkdir artifacts
          copy Steam\${{ matrix.bindir }}\Steam.dll artifacts\Steam.dll
          copy Steam\${{ matrix.bindir }}\Steam.pdb artifacts\Steam.pdb
          copy Steam\steam\rev.ini artifacts\rev.ini
          copy Steam\steam\revApps.ini artifacts\revApps.ini

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.outname }}
          path: artifacts
          if-no-files-found: error
  build-linux:
    name: Linux

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Install 32-bit toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386

      - name: Run CMake
        shell: bash
        working-directory: Steam/steam
        run: cmake -B ./build -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"

      - name: Build
        shell: bash
        working-directory: Steam/steam
        run: cmake --build ./build

      - name: Prepare files for packaging
        shell: bash
        run: |
          mkdir ./artifacts
          cp ./Steam/steam/build/libsteam.so ./artifacts/libsteam.so
          cp ./Steam/steam/build/libsteamvalidateuseridtickets.so ./artifacts/libsteamvalidateuseridtickets.so
          cp ./Steam/steam/rev.ini ./artifacts/rev.ini
          cp ./Steam/steam/revApps.ini ./artifacts/revApps.ini

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReviveEmu-Linux
          path: artifacts
          if-no-files-found: error
  create-release:
    name: Create release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Display downloaded artifacts
        run: find ./artifacts/

      - name: Create release files
        run: |
          mkdir release
          pushd ./artifacts/
          for DIR in *; do
            pushd $DIR
            zip -r9 ../../release/$DIR.zip .
            popd
          done
          popd

      - name: Create rolling release
        if: github.ref == 'refs/heads/main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest rolling release"
          files: |
            ./release/*
